"""add daily limits

Revision ID: 0b56e3aceb9b
Revises: 0007_ingestion_module
Create Date: 2026-05-05 15:32:19.463992

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0008'
down_revision = '0007_ingestion_module'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('daily_new_limit', sa.Integer(), nullable=False),
    sa.Column('daily_review_limit', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_settings_user_id'), 'user_settings', ['user_id'], unique=True)
    
    op.add_column('study_sessions', sa.Column('new_cards_reviewed', sa.Integer(), server_default='0', nullable=False))
    op.add_column('study_sessions', sa.Column('review_cards_reviewed', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('study_sessions', 'review_cards_reviewed')
    op.drop_column('study_sessions', 'new_cards_reviewed')
    
    op.drop_index(op.f('ix_user_settings_user_id'), table_name='user_settings')
    op.drop_table('user_settings')
    # ### end Alembic commands ###

